name: push-to-master

env:
  DOCKER_REPOSITORY: 'alvarogarciafer/to-do-api'
  TEST_IMAGE_TAG: 'test'
  CONTAINER_NAME: 'to-do-api'
  NODE_ENV: 'production'
  PORT: '3000'

on:
  push:
    branches: [ master ]

jobs:
  # test:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@master
          
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@master

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  #     - name: Build and push Docker images
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.TEST_IMAGE_TAG }}

  #     - name: Run linter
  #       run: |
  #         docker container run \
  #         --rm \
  #         ${{ env.DOCKER_REPOSITORY }}:${{ env.TEST_IMAGE_TAG }} \
  #         run linter

  #     - name: Run unit tests
  #       run: |
  #         docker container run \
  #         --rm \
  #         ${{ env.DOCKER_REPOSITORY }}:${{ env.TEST_IMAGE_TAG }} \
  #         test

  build:
    needs: test
    runs-on: self-hosted
    outputs:
      tagname: ${{ steps.action-autotag.outputs.tagname }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Autotag package
        uses: butlerlogic/action-autotag@stable
        id: action-autotag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          strategy: package
          root: to-do-api/to-do-api
          tag_prefix: v

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ steps.action-autotag.outputs.tagname }}
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Deploy container
        run: |
          docker container stop ${{ env.CONTAINER_NAME}} || true
          docker container rm ${{ env.CONTAINER_NAME}} || true
          echo "NODE_ENV=${{ env.NODE_ENV }}" >> .env
          docker container run \
          --env-file .env \
          --publish ${{ env.PORT }}:3000 \
          --name ${{ env.CONTAINER_NAME}} \
          --detach \
          --restart unless-stopped \
          ${{ env.DOCKER_REPOSITORY}}:${{ needs.build.outputs.tagname}} \
          start
          rm .env
