name: push-tag

env:
  DOCKER_HUB_USERNAME: 'alvarogarciafer'
  IMAGE_REPOSITORY: 'alvarogarciafer/to-do-api'
  IMAGE_TAG: 'latest'

on:
  push:
    tags: 
      - '*'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build test image
        run: |
          docker pull ${{ env.IMAGE_REPOSITORY}}:test || true
          docker build \
          --cache-from ${{ env.IMAGE_REPOSITORY}}:test \
          --tag ${{ env.IMAGE_REPOSITORY}}:test \
          .
          docker push ${{ env.IMAGE_REPOSITORY}}:test

      - name: Run linter
        run: |
          docker container run \
          --rm \
          ${{ env.IMAGE_REPOSITORY}}:test \
          run linter

      - name: Run unit tests
        run: |
          docker container run \
          --rm \
          ${{ env.IMAGE_REPOSITORY}}:test \
          test

  build:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB }}

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Build image
        run: |
          docker pull ${{ env.IMAGE_REPOSITORY}}:${{ env.IMAGE_TAG}}
          docker tag ${{ env.IMAGE_REPOSITORY}}:${{ env.IMAGE_TAG}} ${{ env.IMAGE_REPOSITORY}}:${{ steps.get_version.outputs.version }}
          docker push ${{ env.IMAGE_REPOSITORY}}:${{ steps.get_version.outputs.version }}
