name: stop and remove

on: 
  workflow_dispatch:

jobs:
  stop_and_remove:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers
        run: |
          echo "NODE_ENV=production" >> .env
          echo "MONGODB_HOST=mongo" >> .env
          echo "MONGODB_PORT=27017" >> .env
          echo "MONGODB_DATABASE=notebook" >> .env
          echo "TO_DO_API_TAG=latest" >> .env
          echo "TO_DO_API_PORT=3000" >> .env
          docker-compose down
          rm .env
